name: gdal-build
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Default Python version, will be overridden by matrix
  - gdal=3.10.2
  - numpy
  - cmake
  - wheel
  - cibuildwheel
  - pytest
  - pip
  - pip:
    - setuptools>=77.0.3
