name: gdal-build
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Default Python version, will be overridden by matrix
  - gdal=3.10.2
  - numpy>=2.0.0  # For Python >= 3.9
  - cmake
  - wheel
  - cibuildwheel
  - pytest
  - pip
  - compilers  # For building C extensions
  - pip:
    - setuptools>=67.0.0
    - oldest-supported-numpy  # For Python 3.8
