name: Build GDAL Wheels

on:
  push:
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to build for (leave empty for all)'
        required: false
        default: ''
        type: string
      gdal_version:
        description: 'GDAL version to build (default: latest released)'
        required: false
        default: ''
        type: string

env:
  GDAL_VERSION: ${{ github.event.inputs.gdal_version || 'v3.10.2' }}

jobs:
  # First stage: Build GDAL once
  build_gdal:
    name: Build GDAL on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout wheels repository
        uses: actions/checkout@v4
        with:
          path: gdal-wheels

      - name: Configure Git for long paths on Windows
        run: |
          git config --system core.longpaths true

      - name: Checkout GDAL source
        uses: actions/checkout@v4
        with:
          repository: OSGeo/gdal
          ref: ${{ env.GDAL_VERSION }}
          path: gdal-source
          fetch-depth: 0
          submodules: recursive

      - name: Install GDAL dependencies with vcpkg
        shell: cmd
        run: |
          cd C:/vcpkg
          vcpkg install proj sqlite3 curl tiff gdal[core] --triplet=x64-windows

      - name: Build GDAL
        shell: cmd
        run: |
          cd gdal-source
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=../install -DBUILD_SHARED_LIBS=ON -DUSE_EXTERNAL_LIBS=ON -DBUILD_PYTHON_BINDINGS=ON ..
          cmake --build . --config Release --target python_bindings
          cmake --build . --config Release --target install

      - name: Cache GDAL build
        uses: actions/cache/save@v4
        with:
          path: |
            gdal-source/install
            C:/vcpkg/installed
          key: gdal-${{ env.GDAL_VERSION }}-${{ github.sha }}

  # Second stage: Build wheels for each Python version
  build_wheels:
    name: Build wheels for Python ${{ matrix.python-version }}
    needs: build_gdal
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.9.*'
          - '3.10.*'
          - '3.11.*'
          - '3.12.*'
          - '3.13.*'

    steps:
      - name: Checkout wheels repository
        uses: actions/checkout@v4
        with:
          path: gdal-wheels

      - name: Configure Git for long paths on Windows
        run: |
          git config --system core.longpaths true

      - name: Checkout GDAL source
        uses: actions/checkout@v4
        with:
          repository: OSGeo/gdal
          ref: ${{ env.GDAL_VERSION }}
          path: gdal-source
          fetch-depth: 0
          submodules: recursive

      - name: Restore GDAL build
        uses: actions/cache/restore@v4
        with:
          path: |
            gdal-source/install
            C:/vcpkg/installed
          key: gdal-${{ env.GDAL_VERSION }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Create pyproject.toml
        working-directory: gdal-source
        run: |
          echo "[build-system]" > pyproject.toml
          echo "requires = [" >> pyproject.toml
          echo "    \"setuptools>=77.0.3\"," >> pyproject.toml
          echo "    \"wheel\"," >> pyproject.toml
          echo "]" >> pyproject.toml
          echo "build-backend = \"setuptools.build_meta\"" >> pyproject.toml
          echo "[tool.cibuildwheel]" >> pyproject.toml
          echo "build-verbosity = 1" >> pyproject.toml
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel build cibuildwheel numpy

      - name: Build wheels
        env:
          CIBW_BUILD: >-
            ${{ matrix.python-version == '3.9.*' && 'cp39-win_amd64' ||
                matrix.python-version == '3.10.*' && 'cp310-win_amd64' ||
                matrix.python-version == '3.11.*' && 'cp311-win_amd64' ||
                matrix.python-version == '3.12.*' && 'cp312-win_amd64' ||
                matrix.python-version == '3.13.*' && 'cp313-win_amd64' }}
          CIBW_ARCHS: auto64
          CIBW_BEFORE_BUILD: >-
            python -m pip install numpy
          CIBW_ENVIRONMENT: >-
            GDAL_HOME="C:/vcpkg/installed/x64-windows"
            CMAKE_PREFIX_PATH="C:/vcpkg/installed/x64-windows"
            GDAL_CONFIG="gdal-source/install/bin/gdal-config"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: >-
            cd {package} &&
            pytest -xvs || echo "Tests completed with warnings"
        working-directory: gdal-source/swig/python
        run: |
          python -m cibuildwheel --output-dir ../../wheelhouse
      
      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-python${{ matrix.python-version }}
          path: gdal-source/wheelhouse/*.whl
          if-no-files-found: error

  # Only triggered for tagged releases
  create_release:
    name: Create GitHub Release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: GDAL Wheels Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: dist/*.whl
