name: Build GDAL Wheels (Simple)

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to build for (default: 3.11)'
        required: false
        default: '3.11'
        type: string
      gdal_version:
        description: 'GDAL version to build (default: latest released)'
        required: false
        default: 'v3.10.2'
        type: string

env:
  GDAL_VERSION: ${{ github.event.inputs.gdal_version || 'v3.10.2' }}

jobs:
  build_wheels:
    name: Build wheels for Python ${{ github.event.inputs.python_version || '3.11' }}
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout wheels repository
        uses: actions/checkout@v4
        with:
          path: gdal-wheels

      - name: Configure Git for long paths on Windows
        run: |
          git config --system core.longpaths true

      - name: Checkout GDAL source
        uses: actions/checkout@v4
        with:
          repository: OSGeo/gdal
          ref: ${{ env.GDAL_VERSION }}
          path: gdal-source
          fetch-depth: 0
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version || '3.11' }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy setuptools wheel build cibuildwheel

      - name: Install GDAL dependencies
        run: |
          choco install -y vcpkg
          vcpkg install proj sqlite3 curl tiff zlib openssl --triplet=x64-windows

      - name: Set up Visual Studio environment
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64
          echo PATH=%PATH%>> %GITHUB_ENV%
          echo INCLUDE=%INCLUDE%>> %GITHUB_ENV%
          echo LIB=%LIB%>> %GITHUB_ENV%
          echo LIBPATH=%LIBPATH%>> %GITHUB_ENV%

      - name: Build GDAL
        shell: cmd
        run: |
          cd gdal-source
          mkdir build
          cd build
          cmake .. ^
            -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
            -DCMAKE_INSTALL_PREFIX=../install ^
            -DBUILD_SHARED_LIBS=ON ^
            -DBUILD_PYTHON_BINDINGS=ON ^
            -DGDAL_USE_JPEG=ON ^
            -DGDAL_USE_PNG=ON ^
            -DGDAL_USE_ZLIB=ON ^
            -DGDAL_USE_CURL=ON ^
            -DGDAL_USE_CRYPTO=ON ^
            -DGDAL_USE_OPENSSL=ON ^
            -DGDAL_USE_ZLIB_INTERNAL=ON ^
            -DACCEPT_MISSING_SQLITE3_RTREE=ON
          cmake --build . --config Release --target python_bindings
          cmake --build . --config Release --target install

      - name: Build wheels
        env:
          CIBW_BUILD: ${{ github.event.inputs.python_version == '3.9' && 'cp39-win_amd64' ||
                          github.event.inputs.python_version == '3.10' && 'cp310-win_amd64' ||
                          github.event.inputs.python_version == '3.11' && 'cp311-win_amd64' ||
                          github.event.inputs.python_version == '3.12' && 'cp312-win_amd64' ||
                          'cp311-win_amd64' }}
          CIBW_ARCHS: auto64
          CIBW_BEFORE_BUILD: "pip install numpy"
          CIBW_ENVIRONMENT: >-
            GDAL_HOME="D:/a/gdal-wheels/gdal-wheels/gdal-source/install"
            GDAL_DATA="D:/a/gdal-wheels/gdal-wheels/gdal-source/install/share/gdal"
            PROJ_LIB="C:/vcpkg/installed/x64-windows/share/proj"
            OPENSSL_ROOT_DIR="C:/vcpkg/installed/x64-windows"
          CIBW_REPAIR_WHEEL_COMMAND: ""
        working-directory: gdal-source/swig/python
        run: |
          python -m cibuildwheel --output-dir ../../wheelhouse

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-simple-python${{ github.event.inputs.python_version || '3.11' }}
          path: gdal-source/wheelhouse/*.whl
          if-no-files-found: error

  create_release:
    name: Create GitHub Release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: GDAL Wheels Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: dist/*.whl
